"""empty message

Revision ID: d87725be28ef
Revises: 5e0a0bf71dda
Create Date: 2021-05-26 16:01:29.245922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd87725be28ef'
down_revision = '5e0a0bf71dda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract__customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('billing_date', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('username')
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infrequent_customers',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.TEXT(), nullable=True),
    sa.Column('card_info', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.create_table('warehouses',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('pName', sa.TEXT(), nullable=True),
    sa.Column('stock', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('pName', sa.TEXT(), nullable=True),
    sa.Column('unit_sales', sa.INTEGER(), nullable=True),
    sa.Column('unit_price', sa.INTEGER(), nullable=True),
    sa.Column('total_price', sa.INTEGER(), nullable=True),
    sa.Column('store_region', sa.TEXT(), nullable=True),
    sa.Column('date', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manufacturers',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('manu_name', sa.TEXT(), nullable=True),
    sa.Column('pName', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('store_region', sa.TEXT(), nullable=True),
    sa.Column('pName', sa.TEXT(), nullable=True),
    sa.Column('stock', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('contract__customers')
    # ### end Alembic commands ###
